CREATE DATABASE EXCE;
use EXCE;


CREATE TABLE SUPERMERCADO(
ID_DO_ITEM INT primary key NOT NULL,
ID_FORNECEDOR INT NOT NULL,
ALIMENTOS VARCHAR ( 30 ) NOT NULL,
ID_SETOR VARCHAR ( 30 ) NOT NULL,
ESTOQUE INT NOT NULL,
ID_RETIRADA VARCHAR ( 30 ) NOT NULL,
QUANTIDADE_DE_PRODUTOS INT NOT NULL,
PREÇO_UNITARIO VARCHAR ( 30 ) NOT NULL,
SALDO_TOTAL VARCHAR ( 30 ) NOT NULL);

CREATE TABLE ALIMENTOS(
ID_DO_ITEM INT PRIMARY KEY NOT NULL,
ALIMENTOS VARCHAR( 30 ) NOT NULL,
UNIDADE VARCHAR( 30 ) NOT NULL ,
ESTOQUE INT NOT NULL ,
MARCA VARCHAR( 30 ) NOT NULL ,
SALDO_TOTAL  VARCHAR( 30 ) NOT NULL );

CREATE TABLE FATURAMENTO(
ID_DO_ITEM INT PRIMARY KEY NOT NULL,
ID_RETIRADA VARCHAR(30) NOT NULL,
PREÇO_UNITARIO VARCHAR(30) NOT NULL,
SALDO_TOTAL VARCHAR(30) NOT NULL,
META_MES VARCHAR(30) NOT NULL);

CREATE TABLE ITEM(
ID_DO_ITEM INT PRIMARY KEY NOT NULL ,
ALIMENTOS VARCHAR(30) NOT NULL,
ESTOQUE INT NOT NULL,
CONDICOES VARCHAR(30) NOT NULL);


CREATE TABLE RETIRADA_DIARIA(
ID_RETIRADA int primary key NOT NULL,
RETIRADOS VARCHAR(30) NOT NULL,
ESTOQUE INT NOT NULL,
RESTOU INT);


CREATE TABLE FORNECEDOR (
ID_FORNECEDOR INT PRIMARY KEY NOT NULL,
MARCA VARCHAR(30) NOT NULL,
ALIMENTOS VARCHAR(30) NOT NULL,
PREÇO_UNITARIO VARCHAR(30) NOT NULL);

CREATE TABLE SETORR(
ID_SETOR VARCHAR(50) PRIMARY KEY NOT NULL,
SETORES VARCHAR(50) NOT NULL,
MARCA VARCHAR(50) NOT NULL);

DROP TABLE SETORR;

select*from retirada_diaria;
select*from FATURAMENTO;
select*from supermercado;
select*from ALIMENTOS;
select*from ITEM;
select*from fornecedor;
select*from SETOR;

drop table fornecedor;

alter table SUPERMERCADO add constraint FK_SUPERMERCADO_FORNECEDOR foreign key (ID_FORNECEDOR) references SUPERMERCADO(ID_FORNECEDOR)
on delete restrict;


alter table ALIMENTOS add constraint FK_ALIMENTOS_SUPERMERCADO foreign key (ID_DO_ITEM) references SUPERMERCADO(ID_DO_ITEM)
on delete cascade;
select*from SUPERMERCADO;

alter table RETIRADA_DIARIA add constraint FK_RETIRADA_DIARIA_SUPERMERCADO foreign key (ID_RETIRADA) references SUPERMERCADO(ID_RETIRADA)
on delete cascade;

alter table SUPERMERCADO add constraint FK_SUPERMERCADO_ITEM foreign key (ALIMENTOS) references ITEM(ALIMENTOS)
on delete cascade;

alter table FORNECEDOR add constraint FK_FORNECEDOR_SUPERMERCADO foreign key (PREÇO_UNITARIO) references SUPERMERCADO(PREÇO_UNITARIO)
on delete cascade;



select ALIMENTOS, ID_SETOR
from ITEM inner join SETORR on A.ID_SETORR = B.ID_SETORR;


select ALIMENTOS from ALIMENTOS order by ALIMENTOS desc;
select ID_DO_ITEM from ITEM order by ID_DO_ITEM asc;
select ID_SETOR from SETORR where ID_SETOR = 'A' order by ID_SETOR;
select ID_FORNECEDOR from SUPERMERCADO where ID_FORNECEDOR = '65'  order by ID_FORNECEDOR;
select ID_RETIRADA from RETIRADA_DIARIA order by ID_RETIRADA desc;


select ID_FORNECEDOR from FORNECEDOR group by ID_FORNECEDOR;
select ID_RETIRADA from RETIRADA_DIARIA group by ID_RETIRADA;
select ALIMENTOS from SUPERMERCADO group by ALIMENTOS desc;
select ID_DO_ITEM from ITEM group by ID_DO_ITEM;


select ID_FORNECEDOR, ID_DO_ITEM from FORNECEDOR
inner join SUPERMERCADO on Laranjas.ALIMENTOS = Frango.ALIMENTOS
order by FORNECEDOR desc;


select ESTOQUE , ALIMENTOS from ITEM
inner join SUPERMERCADO  on ESTOQUE = ESTOQUE
order by ALIMENTOS ASC;

select sum(ID_FORNECEDOR) from FORNECEDOR;
select round(avg(ID_DO_ITEM)) from ITEM;
select sum(ID_SETOR) FROM SETORR;
select sum(ALIMENTOS) from SUPERMERCADO;
select round(avg(SALDO_TOTAL)) from FATURAMENTO;
select round(avg(ID_FORNECEDOR)) from FORNECEDOR;
select sum(ESTOQUE) from ITEM;


create view ID_FORNECEDOR_65
as select ID_FORNECEDOR from SUPERMERCADO
where ID_DO_ITEM like '65';



create view ID_DO_ITEM_55
as select ID_DO_ITEM from SUPERMERCADO
where ID_FORNECEDOR like '55';

select*from ID_DO_ITEM_55;

create view ID_DO_ITEM_22
as select ID_DO_ITEM from SUPERMERCADO
where ID_FORNECEDOR like '22';

select*from ID_DO_ITEM_22;

create view ID_DO_ITEM_11
as select ID_DO_ITEM from SUPERMERCADO
where ID_FORNECEDOR like '11';

select*from ID_DO_ITEM_11;

create view ID_DO_ITEM_88
as select ID_DO_ITEM from SUPERMERCADO
where ID_FORNECEDOR like '88';

select*from ID_DO_ITEM_88;

create view ID_DO_ITEM_12
as select ID_DO_ITEM from SUPERMERCADO
where ID_FORNECEDOR like '12';

select*from ID_DO_ITEM_12;
start transaction;

INSERT INTO Item VALUES ('Laranjas', 'Pera');
SAVEPOINT ITEMLaranjas;
ROLLBACK to ITEMLarnjas;

INSERT INTO ID_FORNECEDOR VALUES ('94', '2');
SAVEPOINT ID_FORNECEDOR94;
 ROLLBACK TO ID_FORNECEDOR94;

INSERT INTO setor VALUES ('A','Z');
SAVEPOINT setorZ;
ROLLBACK TO setorZ;

CREATE USER PADARIA;
CREATE USER REFRIGERANTE;
CREATE USER MASSAS;

DROP USER  PADARIA;
DROP USER REFRIGERANTE;
DROP USER MASSAS;

GRANT ALL ON ID_SETOR.SETORR_A TO PADARIA;
GRANT ALL ON ID_SETOR.SETORR_C TO PADARIA;
GRANT ALL ON ID_SETOR.SETORR_Z TO PADARIA;
GRANT ALL ON ID_SETOR.SETORR_E TO PADARIA;
GRANT ALL ON ID_SETOR.SETORR_F TO PADARIA;
